### ISSUE TITLE
Committee position of None still makes a them a committee member.

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#110]
In the 'University Members' section of the admin panel. When adding a new person and selecting their committee position as None it still makes them committee. Think this is due to it expecting non-committee to be '0' and it inserts it as 'None'

**Comment by addshore** [comment]
Yes :/
Looks like a bug!

Should be empty string, 0 or null in order to not be a committee member!

**Comment by oshotton** [comment]
Has this been fixed? Not noticed it happen in a while! :)

**Comment by addshore** [comment]
Not been fixed :)

**Comment by oshotton** [comment]
Closing and seems to of been fixed
