### ISSUE TITLE
Universities should have an email address registered in the db

### ISSUE THREAD

**Issue by addshore** [SWAuk/com_swa#116]
this would mean that we could also provide a contact form & send bulk emails to all clubs....

Email address could be optional and if not provided then just send to all committee members emails (from user tables)

**Comment by Beaker69** [comment]
President.[uniname]@swa.co.uk forwarders always used to be updated each year so it went to the president. This used to be rather time consuming but you might be able to automate it so whoever in the database is a president for uni X gets forwarded all emails to president.[X]@swa.co.uk... That way all you need so is assign someone president powers and they get all emails from then on. Works when you have more than one pres from a uni too..

Sent from my iPhone

On 8 Oct 2015, at 20:03, addshore <notifications@github.com> wrote:

this would mean that we could also provide a contact form & send bulk emails to all clubs....

**Comment by addshore** [comment]
Yeh, basically I want to avoid having to change the forwarders each year.
It will be the university committees responsibility to add their new committee members to the site, remove the old ones and update the email address etc.

**Comment by addshore** [comment]
We are killing the forwarders (as we can easily email them directly now if we want).
Thus closing this!
