### ISSUE TITLE
Date picker not displaying properly in Account -> My Qualifications 

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#120]

**Comment by addshore** [comment]
Screenshot or it didn't happen ;)

**Comment by oshotton** [comment]
![image](https://cloud.githubusercontent.com/assets/5147961/10418136/74342e50-704a-11e5-92dc-f78192312f61.png)

**Comment by addshore** [comment]
Ahh yeh, I have a post it note on my desk saying we should fix this ;)
This is the inbuilt date picker from joomla so we likely just need to add some css to the template to make it include an icon etc and be on the write line!

**Comment by oshotton** [comment]
New theme has fixed this issue
