### ISSUE TITLE
Club committee should be able to register all members with 1 button press

### ISSUE THREAD

**Issue by addshore** [SWAuk/com_swa#130]

**Comment by oshotton** [comment]
Yeah I was thinking about this, maybe have a check box to enable/disable individual registration in 'club settings'. This way, if individual registration is disabled, new members of a club will also be registered.

Could be implemented by a flag in the university table, website first checks if individual registration is enabled/disabled, if enabled check the event_registration table to see if they have been registered, if disabled allow them to buy ticket.

Can discuss later :)

**Comment by addshore** [comment]
Hmmm, yeh, that could be quite nice..
