### ISSUE TITLE
How to register members for one of two events on the same day?

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#132]
There is going to be a Birmingham Core event and a PlymEx Wave event on the same weekend so how to select which one to register a member for? Could have a popup after clicking register next to members name to select what event to register for.

**Comment by addshore** [comment]
This is already handled!

For example currently you see this
![image](https://cloud.githubusercontent.com/assets/3308769/10869268/ff3ff1b8-80a9-11e5-9abb-e195124cdc3b.png)

For 2 events, there will be 2 links there!

**Comment by oshotton** [comment]
Okay sweet! :)
