### ISSUE TITLE
Add "notes" column to the tickets table

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#134]
Add a "notes" column to add specific notes about certain tickets. E.g "paying in cash on arrival", "please host with XYZ uni" etc etc.

**Comment by addshore** [comment]
HAHAHAA https://github.com/SWAuk/com_swa/issues/133

**Comment by oshotton** [comment]
I don't get why this is funny!! :'(

**Comment by addshore** [comment]
Because I thought of exactly the same thing 2 weeks about and opened an issue :P

**Comment by oshotton** [comment]
Oooohhhhh really sowwwyy!! :( bahahahaha!!!!
