### ISSUE TITLE
RESULTS - Team race series sorting is wrong

### ISSUE THREAD

**Issue by addshore** [SWAuk/com_swa#149]

**Comment by Beaker69** [comment]
How's it all going with the results system? Following my calculations??
B

**Comment by addshore** [comment]
@Beaker69 Yep, basically done.
Mainly going from www.studentwindsurfing.co.uk/events/competition-rules

Just got to do this bit and work out how its done,

> 1st place in Intermediates scores last place in Adv +1. 1st place in Beginners scores last place in Int +1.

#148
