### ISSUE TITLE
Link to download csv of all event attendees under the tickets sold table

### ISSUE THREAD

**Issue by oshotton** [SWAuk/com_swa#169]

**Comment by addshore** [comment]
Such a link should only be available until the end of the event

**Comment by oshotton** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add Events Attending CSV below ticket sales table](https://trello.com/c/eXzwMvGU/5-add-events-attending-csv-below-ticket-sales-table)

**Comment by oshotton** [comment]
Fixed in https://github.com/SWAuk/com_swa/commit/3263bf475e9fe25a87f4c0fd2525d6ed5fa4df96.
