### ISSUE TITLE
Cookies accept button only half visible, also doesn't work on some browsers

### ISSUE THREAD

**Issue by mduffin95** [SWAuk/com_swa#211]
I think it doesn't work on IE (can't test right now) and I have also had issues on mobile before. This causes the menu bar to be obscured. Might be worth moving it to the bottom of the screen if the underlying issue can't be addressed.

**Comment by oshotton** [comment]
I think the cookie bar is done via a free plugin, there might be settings to move it to the bottom or a better plugin to use.

**Comment by LukeStorry** [comment]
Plugin changed to Folcomedia - Cookies Alert
