### ISSUE TITLE
Consider removing the CopyIn/CopyOut scripts in favour of using OverlayFS

### ISSUE THREAD

**Issue by arontsang** [SWAuk/com_swa#220]
Using OverlayFS to mount the Joomla files in the lower fs and the SWA src files in the upper fs would solve all the issues that the CopyIn/CopyOut scripts are meant to fix.

**Comment by oshotton** [comment]
This is a good idea now that we are using Linux Containers - previously a lot of development happened on windows machines so wouldn't have been possible. It might still be a good idea to keep the copy scripts around for now in case there are people not on Linux or using Docker.

Would you be up for submitting a PR to implement this and update the docs?

**Comment by oshotton** [comment]
Although thinking on this some more...
The structure of the git repo is the same as the structure that Joomla requires for the zip file when installing a plugin. This is different from the structure of the Joomla install once the plugin is installed.

You might be able to get around this by having a read-only merge of 4 layers:
 - folder where Joomla is installed (`$JOOMLA_ROOT`)
 - `src/site` folder in the git repo on top of `$JOOMLA_ROOT/components/com_swa`
 - `src/administrator` folder in the git repo on top of `$JOOMLA_ROOT/administrator/components/com_swa`
 - `swa.xml` file in the git repo on top of `$JOOMLA_ROOT/administrator/components/com_swa/swa.xml`

Other things to consider:
 1. Won't be able to update the Joomla install via the admin panel (probably not an issue as best to pull/rebuild the container than to update in place)
 1. I liked opening the whole Joomla install in my IDE as smart features (e.g. autocomplete) worked better. I think using `overlayfs` would stop this from being possible (at least the way I laid out above).
 1. Is `overlayfs` the best tool for the job or would another union file system be more appropriate? Genuine question, I don't know loads about `overlayfs` and any other union file systems but before we implement anything new we should make sure we are using the best tool for the job.

**Comment by arontsang** [comment]
You are right, come to think about it. There is a much better solution to the problem.

Symlinks.

Simply mount the git repo in the joomla docker container. Add a few symlinks from the joomla folders to the git repo. Et voila.

Added bonus of being all in user space rather than in kernel space, which means you can do it without root or privileged mode docker.

Probably best to implement it as a Docker image.

**Comment by oshotton** [comment]
Symlinks do seem like a better idea. Although, as both the Joomla install and the git repo are local directories mounted into the container you would have to create the symlink after the container is created and not when building the image (otherwise I think the symlinks would be overwritten by the mount points). Perhaps this could go in the `firstSetup.php` script.

Are you looking at contributing to the SWA website again or just dropping off some ideas? =)
