### ISSUE TITLE
Event Ticket names should have a dropdown list of options

### ISSUE THREAD

**Issue by Beaker69** [SWAuk/com_swa#68]
ie for most uni events it could be 
Beg Windsurf
Int Windsurf
Adv Windsurf
XSWA
Instructor
SWA Committee
with option for 'other' which swa committee could use to set it as fancy things for bucs champs or AK

**Comment by addshore** [comment]
Not going to do this, this season worked well with free text!

[--- Commented from Asana.com
#commenter Adam Shorland
---[aa]
