### ISSUE TITLE
Ticket table should contain the amount paid for the ticket through nochex

### ISSUE THREAD

**Issue by Beaker69** [SWAuk/com_swa#71]
if this is a list of paid ticket people, we have had issues in the past where somehow there is always one or two people at AK who have paid the right amount for say an xswa ticket but have a windsurf ticket against their name. being able to view the amoutn paid (as confirmed by nochex) against the type of ticket they have helps us track these people down and sort out what they should have.

**Comment by addshore** [comment]
Done
