### ISSUE TITLE
Date formats as ddmmyyyy instead of yyyymmdd

### ISSUE THREAD

**Issue by Beaker69** [SWAuk/com_swa#84]
Can we please get the database to store as uk style ddmmyyyy rather than yyyymmdd. if not then the dates should at least be displayed on the site with a decent legible format rather than the raw yyyymmdd which no one really uses...

**Comment by addshore** [comment]
Okay, storage will still be YYYMMDD but now for the frontend views we format this nicely.

We will leave the backend showing exactly what is in the db though
