### ISSUE TITLE
Include dietary requirements in membership!!!!!!!!!!!!

### ISSUE THREAD

**Issue by addshore** [SWAuk/com_swa#93]
Something that could help people organising events!

**Comment by Beaker69** [comment]
This could potentially be massively confusing to organise for hosts depending on where people end up sleeping. Too many dietary options these days!

Sent from my iPhone

On 28 Apr 2015, at 12:10, "addshore" <notifications@github.com> wrote:

Closed #93 via a82041a.

**Comment by addshore** [comment]
But right now the situation is no better, people turn up, then having nothing to eat! :/ then people running the event have to try and sort that out, at least this way they would know in advance
